# config/routes.yaml
# Load attribute-based routes from controllers
controllers:
    resource: ../src/Controller/
    type: attribute

# Framework routes (for dev/prod errors)
when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.php'
        prefix: /_error

when@prod:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.php'
        prefix: /_error
